
<h1>View KPelamarT #<?php echo $model->pelamar_id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'pelamar_id',
		'departement_id',
		'pendidikan_id',
		'propinsi_id',
		'karyawan_id',
		'kabupatenkota_id',
		'jabatan_id',
		'jurusan_id',
		'tgllowongan',
		'jenisidentitas',
		'noidentitas',
		'nama_pelamar',
		'nama_keluarga',
		'tempatlahir_pelamar',
		'tgl_lahirpelamar',
		'jeniskelamin',
		'statusperkawinan',
		'jmlanak',
		'alamat_pelamar',
		'kodepos',
		'agama',
		'alamatemail',
		'notelp_karyawan',
		'nomobile_pelamar',
		'warganegara_pelamar',
		'photopelamar',
		'gajiygdiharapkan',
		'tglditerima',
		'tglmulaibekerja',
		'keterangan_pelamar',
		'karyawan_aktif',
        'fileCV_Pelamar',
	),
)); ?>
